### ISSUE TITLE
Not able to remove language from navbar menu

### ISSUE THREAD

**Issue by lordarcadius** [spech66/materialize-bp-hugo-theme#1]
Hey man, I am not able to remove the Deutsche language button from the menu of navbar. I can't find any config in .toml file. Please help. 
![Screenshot from 2019-11-17 00-30-21](https://user-images.githubusercontent.com/13603567/68997925-e0261280-08d1-11ea-8ffa-fc37a99a9c35.png)

**Comment by spech66** [comment]
Are you using the example page? There is a file for testing at
`exampleSite/content/post/100-multilang/index.de.md`

**Comment by lordarcadius** [comment]
Thanks a lot bruh. Fixed it.
